### ISSUE TITLE
Error with vibe-d HTTPServerSettings

### ISSUE THREAD

**Issue by vetio** [carlor/yamkeys#4]
Trying to compile yamkeys as in the tutorial leads to a compile time error:
<pre>
../../../.dub/packages/yamkeys-master/source/yamkeys.d-mixin-224-mixin-232(232): Error: template yamkeys.Configuration.load cannot deduce function from argument types !(int)(int, Node), candidates are:
../../../.dub/packages/yamkeys-master/source/yamkeys.d(65):        yamkeys.Configuration.load(T)(ref T obj, string label = defaultName!T)
../../../.dub/packages/yamkeys-master/source/yamkeys.d(174):        yamkeys.Configuration.load(T)(ref T obj, Node node)
../../../.dub/packages/yamkeys-master/source/yamkeys.d-mixin-224-mixin-235(235): Error: template yamkeys.Configuration.load cannot deduce function from argument types !(bool delegate(scope SSLPeerValidationData))(bool delegate(scope SSLPeerValidationData data), Node), candidates are:
../../../.dub/packages/yamkeys-master/source/yamkeys.d(65):        yamkeys.Configuration.load(T)(ref T obj, string label = defaultName!T)
../../../.dub/packages/yamkeys-master/source/yamkeys.d(174):        yamkeys.Configuration.load(T)(ref T obj, Node node)
../../../.dub/packages/yamkeys-master/source/yamkeys.d-mixin-224-mixin-253(253): Error: template instance yamkeys.Configuration.load!(SSLContext) error instantiating
../../../.dub/packages/yamkeys-master/source/yamkeys.d(73):        instantiated from here: load!(HTTPServerSettings)
</pre>

**Comment by carlor** [comment]
Should be fixed by be11c75.
